/* quotebank.js — place in the same folder as typemaster.html */
var QUOTES = [
  {text:"The future rewards those who keep moving forward. Change will not come if we wait for someone else or some other time.",author:"Barack Obama"},
  {text:"Yes we can build a better future, but it requires responsibility. Progress begins when ordinary people decide to participate.",author:"Barack Obama"},
  {text:"Hope is not blind optimism. Hope is the belief that something better is possible if we work for it.",author:"Barack Obama"},
  {text:"If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.",author:"Barack Obama"},
  {text:"We are the change that we seek. Waiting for heroes only delays the work that belongs to us.",author:"Barack Obama"},
  {text:"A democracy thrives when citizens stay engaged. Silence is often the greatest threat to freedom.",author:"Barack Obama"},
  {text:"Real leadership is not about power. It is about responsibility to the people you serve.",author:"Barack Obama"},
  {text:"Imagination is more important than knowledge. Knowledge is limited but imagination encircles the world.",author:"Albert Einstein"},
  {text:"Life is like riding a bicycle. To keep your balance, you must keep moving.",author:"Albert Einstein"},
  {text:"A person who never made a mistake never tried anything new. Failure is simply the evidence of experimentation.",author:"Albert Einstein"},
  {text:"The important thing is not to stop questioning. Curiosity has its own reason for existing.",author:"Albert Einstein"},
  {text:"Logic will get you from A to B. Imagination will take you everywhere.",author:"Albert Einstein"},
  {text:"Great spirits have always encountered violent opposition from mediocre minds. Innovation disturbs comfort.",author:"Albert Einstein"},
  {text:"He who has a why to live can bear almost any how. Purpose gives strength to endure suffering.",author:"Friedrich Nietzsche"},
  {text:"That which does not kill us makes us stronger. Adversity sharpens the spirit.",author:"Friedrich Nietzsche"},
  {text:"There are no facts, only interpretations. Perspective shapes the world we experience.",author:"Friedrich Nietzsche"},
  {text:"The snake which cannot shed its skin must perish. Minds that refuse change suffer the same fate.",author:"Friedrich Nietzsche"},
  {text:"The individual has always had to struggle to keep from being overwhelmed by the tribe. Courage begins with independence.",author:"Friedrich Nietzsche"},
  {text:"The higher we soar, the smaller we appear to those who cannot fly. Greatness is often misunderstood.",author:"Friedrich Nietzsche"},
  {text:"A book must be the axe for the frozen sea within us. Literature should awaken what lies dormant.",author:"Franz Kafka"},
  {text:"You are free, and that is why you are lost. Freedom without direction creates confusion.",author:"Franz Kafka"},
  {text:"Start with what is right rather than what is acceptable. Integrity is rarely convenient.",author:"Franz Kafka"},
  {text:"In the fight between you and the world, back the world. Reality does not negotiate with emotion.",author:"Franz Kafka"},
  {text:"Anyone who keeps the ability to see beauty never grows old. Wonder protects the spirit.",author:"Franz Kafka"},
  {text:"The world itself is just one big hoax. We are just puppets for the corporations.",author:"Mr. Robot"},
  {text:"Power belongs to the people that take it. Systems only survive because we believe in them.",author:"Mr. Robot"},
  {text:"Sometimes the truth is the most dangerous virus. Once people see it, they cannot unsee it.",author:"Mr. Robot"},
  {text:"The system is not broken. It was built this way.",author:"Mr. Robot"},
  {text:"Reality can be rewritten by those who control the narrative. Information is the ultimate weapon.",author:"Mr. Robot"},
  {text:"If you have a sense of humor about life, you can survive almost anything. Laughter is a form of armor.",author:"Jimmy Carr"},
  {text:"Comedy is simply honesty with timing. Truth becomes funny when you remove the filters.",author:"Jimmy Carr"},
  {text:"The trick to life is perspective. Change the angle and the problem changes shape.",author:"Jimmy Carr"},
  {text:"A joke is a tiny rebellion against seriousness. Humor disrupts the ordinary.",author:"Jimmy Carr"},
  {text:"The best comedians observe what everyone else ignores. Insight hides in everyday moments.",author:"Jimmy Carr"},
  {text:"You are only given a little spark of madness. You must not lose it.",author:"Robin Williams"},
  {text:"No matter what people tell you, words and ideas can change the world.",author:"Robin Williams"},
  {text:"Everyone you meet is fighting a battle you know nothing about. Be kind.",author:"Robin Williams"},
  {text:"The human spirit is stronger than anything that can happen to it. Resilience defines us.",author:"Robin Williams"},
  {text:"Laughter connects people instantly. Humor dissolves barriers.",author:"Robin Williams"},
  {text:"Your value in the marketplace determines your income. Increase your value and your income follows.",author:"Patrick Bet-David"},
  {text:"Execution beats intelligence when intelligence refuses to act. Action compounds results.",author:"Patrick Bet-David"},
  {text:"If you want a bigger future, build bigger skills. Growth is always a skill problem.",author:"Patrick Bet-David"},
  {text:"The best entrepreneurs are obsessed with solving problems. Profit follows usefulness.",author:"Patrick Bet-David"},
  {text:"Great companies are built by people who refuse average standards. Excellence becomes culture.",author:"Patrick Bet-David"},
  {text:"Discipline is remembering what you want most. Short-term impulses lose to long-term clarity.",author:"Chris Williamson"},
  {text:"Modern comfort creates weak minds. Voluntary hardship rebuilds strength.",author:"Chris Williamson"},
  {text:"Self-awareness is a superpower. Most people move through life unconsciously.",author:"Chris Williamson"},
  {text:"Confidence grows when promises to yourself are kept. Integrity begins internally.",author:"Chris Williamson"},
  {text:"A meaningful life is built deliberately. Accidental success is rare.",author:"Chris Williamson"},
  {text:"Success often begins where comfort ends. Growth demands inconvenience.",author:"Unknown"},
  {text:"The most powerful habit is consistency. Small actions repeated daily create massive change.",author:"Unknown"},
  {text:"Patience is a competitive advantage in a distracted world. Focus outlasts hype.",author:"Unknown"},
  {text:"Discipline turns dreams into plans. Plans turn into results.",author:"Unknown"},
  {text:"Curiosity expands intelligence. Questions open doors that answers close.",author:"Unknown"},
  {text:"Consistency is louder than promises. Actions prove commitment.",author:"Unknown"},
  {text:"Momentum builds slowly then suddenly. Persistence triggers breakthroughs.",author:"Unknown"},
  {text:"Strong character grows from repeated discipline. Integrity compounds quietly.",author:"Unknown"},
  {text:"Energy flows where attention goes. Direct it wisely.",author:"Unknown"},
  {text:"Small improvements accumulate dramatically. Marginal gains create massive results.",author:"Unknown"},
  {text:"The future belongs to adaptive minds. Flexibility defeats rigidity.",author:"Unknown"},
  {text:"Knowledge becomes wisdom through application. Use what you learn.",author:"Unknown"}
];
